support thoth-prescription job with the argocd
operate-first/argocd-apps pull request #110
Opened 2021-03-18 20:00 UTC by harshad16

support thoth-prescription job with the argocd
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

2021-03-18 20:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[envs/moc/zero/thoth/OWNERS](https://github.com/operate-first/argocd-apps/blob/main/envs/moc/zero/thoth/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-03-18 23:22 UTC, anishasthana approved these changes
/lgtm

2021-03-18 23:22 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/110#pullrequestreview-615950436" title="LGTM">anishasthana</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[envs/moc/zero/thoth/OWNERS](https://github.com/operate-first/argocd-apps/blob/main/envs/moc/zero/thoth/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-03-19 10:48 UTC, tumido requested changes

2021-03-19 10:48 UTC, tumido commented on envs/moc/zero/thoth/prod/prod-thoth-prescription-sync.yaml
> +    server: 'https://api.ocp4.prod.psi.redhat.com:6443'
@harshad16 ArgoCD in Operate First can't manage workloads within PSI. Please either use an Operate First cluster or deploy this to https://github.com/AICoE/aicoe-cd

2021-03-24 05:19 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-03-24 05:19 UTC, harshad16 commented on envs/moc/zero/thoth/prod/prod-thoth-prescription-sync.yaml
> +    server: 'https://api.ocp4.prod.psi.redhat.com:6443'
Thanks for pointing. i made the copy-paste mistake, i have fixed it.

2021-03-24 11:04 UTC, tumido reviewed
/lgtm

2021-03-24 11:04 UTC, tumido approved these changes
/approve

2021-03-24 11:04 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/110#pullrequestreview-615950436" title="LGTM">anishasthana</a>*, *<a href="https://github.com/operate-first/argocd-apps/pull/110#pullrequestreview-619586547" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[envs/moc/zero/thoth/OWNERS](https://github.com/operate-first/argocd-apps/blob/main/envs/moc/zero/thoth/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-24 11:06 UTC, merged