feat: move ci-prow to smaug
operate-first/argocd-apps pull request #186
Opened 2021-08-31 13:18 UTC by mimotej

Moving ci-prow from zero to smaug

2021-08-31 13:18 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-09-01 12:46 UTC, harshad16 requested changes
lgtm
can you please chnage the destination in the apps:
- https://github.com/operate-first/argocd-apps/blob/f5b678d403dc98e2ee3b255a1276a61c5d5b82aa/envs/moc/smaug/operate-first/ci-prow-test-pods.yaml#L8 to smaug
- https://github.com/operate-first/argocd-apps/blob/f5b678d403dc98e2ee3b255a1276a61c5d5b82aa/envs/moc/smaug/operate-first/ci-prow.yaml#L8 to smaug

2021-09-01 16:54 UTC, harshad16 approved these changes
lgtm
thanks fro all the wokr

2021-09-01 16:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/186#pullrequestreview-744176198" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-09-01 17:01 UTC, tumido approved these changes
/lgtm
/approve

2021-09-01 17:01 UTC, merged

2021-09-01 17:02 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/186#pullrequestreview-744176198" title="Approved">harshad16</a>*, *<a href="https://github.com/operate-first/argocd-apps/pull/186#pullrequestreview-744183550" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->