Move the thoth-station test apps to rick
operate-first/argocd-apps pull request #204
Opened 2021-09-16 19:33 UTC by harshad16

Move the thoth-station test apps to rick
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Depends-on: https://github.com/operate-first/apps/pull/1008
Related-to: https://github.com/thoth-station/thoth-application/issues/1769

2021-09-16 19:33 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-09-16 19:36 UTC, Gregory-Pereira commented
If it's just migrating the namespace then it looks good. I'll let someone else approve to push it through though.

2021-09-16 19:41 UTC, 4n4nd reviewed
/lgtm

2021-09-16 20:32 UTC, HumairAK commented
can you also update: https://github.com/operate-first/argocd-apps/blob/main/projects/thoth.yaml#L8 and add rick

2021-09-17 11:05 UTC, tumido requested changes
Marking @HumairAK's comment as "request changes" https://github.com/operate-first/argocd-apps/pull/204#issuecomment-921224874

Please add the Rick cluster to your project:
https://github.com/operate-first/argocd-apps/blob/b3165a430accd2655131957889f96c13286972fe/projects/thoth.yaml#L8-L10

2021-09-17 11:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **4n4nd** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2021-09-17 11:25 UTC, goern commented
@tumido @HumairAK see https://github.com/operate-first/argocd-apps/pull/209

2021-09-17 13:28 UTC, harshad16 commented
@HumairAK @tumido The required changes are already completed.
Ready for review again

2021-09-17 13:37 UTC, HumairAK commented on envs/emea/rick/thoth/test/test-thoth-investigator.yaml
>      path: investigator/overlays/zero-test
shouldn't this be `rick-test` now?

2021-09-17 18:33 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-09-17 18:33 UTC, harshad16 commented on envs/emea/rick/thoth/test/test-thoth-investigator.yaml
>      path: investigator/overlays/zero-test
Thanks , it is resolved.
PTAL @HumairAK

2021-09-20 13:26 UTC, HumairAK approved these changes
/lgtm
/approve

2021-09-20 13:26 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/204#pullrequestreview-758629643" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-20 13:30 UTC, merged