Move the thoth-station prod apps to smaug
operate-first/argocd-apps pull request #205
Opened 2021-09-16 19:51 UTC by harshad16

Move the thoth-station prod apps to smaug
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/thoth-station/thoth-application/issues/1971

Details:
1. moving all the thoth-station workloads from zero to Smaug
2. As pre-requisites like pvc and ceph is not available, the prod app is currently not added to [kustomization.yaml](https://github.com/harshad16/argocd-apps/blob/26ddf1ff11f64c0290fa2253830d158592a04ec9/envs/moc/smaug/thoth/kustomization.yaml)
3. Bots that are not dependent are switched on.

2021-09-16 19:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-09-16 19:55 UTC, harshad16 commented
/hold
wait for #204

2021-09-17 11:02 UTC, tumido approved these changes
/lgtm
/approve

2021-09-17 11:02 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/205#pullrequestreview-757335429" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-17 11:04 UTC, tumido requested changes
as @HumairAK noted here https://github.com/operate-first/argocd-apps/pull/204#issuecomment-921224874

Please add the smaug cluster to your project:
https://github.com/operate-first/argocd-apps/blob/b3165a430accd2655131957889f96c13286972fe/projects/thoth.yaml#L8-L10

2021-09-17 11:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **tumido** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-09-20 18:31 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-09-20 18:34 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 97972681b3755d824804f065826d1d378602a209 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/operate-first_argocd-apps/205/pre-commit/1440020803012792320) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=argocd-apps&pr=205). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/operate-first/argocd-apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-09-20 19:01 UTC, harshad16 commented
/unhold
Ready for Review

2021-09-21 20:32 UTC, Gregory-Pereira commented on envs/moc/smaug/thoth/prod/kustomization.yaml
>  - prod-thoth-user-api.yaml
Both the file was changed and these components were removed?

2021-09-21 20:33 UTC, Gregory-Pereira reviewed
looks good, just that one question on the review.

2021-09-23 13:10 UTC, harshad16 commented on envs/moc/smaug/thoth/prod/kustomization.yaml
>  - prod-thoth-user-api.yaml
This file is no longer part of the **prod** directory, it is moved to the **bots** directory.

2021-09-28 17:51 UTC, HumairAK approved these changes
/lgtm
/approve

2021-09-28 17:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/205#pullrequestreview-765782854" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-28 17:53 UTC, merged