Creating ArgoCD Project and app for Fybrik
operate-first/argocd-apps pull request #208
Opened 2021-09-16 21:36 UTC by eletonia

This PR replaces the previous `mesh-for-data` ArgoCD project and app with the `fybrik` ArgoCD project and app
Please let us know if the MOC zero cluster the correct place for the app. 

@4n4nd @ronenkat

2021-09-16 21:36 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-09-16 21:36 UTC, sesheta commented
Hi @eletonia. Thanks for your PR.

I'm waiting for a [operate-first](https://github.com/orgs/operate-first/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/operate-first/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-09-17 14:02 UTC, 4n4nd requested changes
Can you move `envs/moc/zero/fybrik/kustomization.yaml` to `envs/moc/smaug/fybrik/`?

2021-09-17 14:33 UTC, eletonia commented on projects/fybrik.yaml
> +      server: 'https://api.zero.massopen.cloud:6443'
@4n4nd Thanks, I changed the server url to the smaug one

2021-09-17 14:43 UTC, 4n4nd commented
/ok-to-test

2021-09-20 12:30 UTC, tumido approved these changes
/lgtm
/approve

2021-09-20 12:31 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/208#pullrequestreview-758570357" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-09-20 12:32 UTC, merged