Add Observatorium App
operate-first/argocd-apps pull request #25
Opened 2020-12-11 19:14 UTC by 4n4nd

Add manifests to create the opf-observatorium argocd app

2020-12-11 19:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **4n4nd** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @4n4nd` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2020-12-11 19:17 UTC, 4n4nd commented
Will still need to add the overlays directory in https://github.com/operate-first/apps/tree/master/observatorium

2020-12-11 19:31 UTC, anishasthana requested changes

2020-12-11 19:31 UTC, anishasthana commented on base/operate-first/observatorium.yaml
> +  syncPolicy:
Let's enable autosync here please.

2020-12-11 19:34 UTC, 4n4nd commented on base/operate-first/observatorium.yaml
> +  syncPolicy:
what's the flag to do that?

2020-12-11 19:36 UTC, HumairAK commented on base/operate-first/observatorium.yaml
> +  syncPolicy:
I'd hold of on this, because it may send argocd on an infinite sync spiral since it can't sync observatorium resources due to [this](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/62)

2020-12-11 19:37 UTC, HumairAK commented
/hold
ArgoCD can't deploy these resources atm blocked by [this](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/62)

2020-12-11 19:45 UTC, 4n4nd commented on base/operate-first/observatorium.yaml
> +  syncPolicy:
added the flag :+1: 
but let's wait on the issue to be fixed before merging

2020-12-11 19:46 UTC, HumairAK approved these changes

2020-12-11 19:46 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/25#pullrequestreview-550528737" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-11 19:46 UTC, HumairAK commented
the actual pr itself lgtm

2020-12-11 20:06 UTC, anishasthana approved these changes

2020-12-11 20:06 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/25#pullrequestreview-550541278" title="Approved">anishasthana</a>*, *<a href="https://github.com/operate-first/argocd-apps/pull/25#pullrequestreview-550528737" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [HumairAK,anishasthana]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-16 10:28 UTC, tumido approved these changes

2020-12-16 10:28 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/25#pullrequestreview-550541278" title="Approved">anishasthana</a>*, *<a href="https://github.com/operate-first/argocd-apps/pull/25#pullrequestreview-550528737" title="Approved">HumairAK</a>*, *<a href="https://github.com/operate-first/argocd-apps/pull/25#pullrequestreview-553549849" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [HumairAK,anishasthana,tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-22 16:28 UTC, 4n4nd commented
@HumairAK does it make sense to merge this now while MOC is down?

2020-12-22 20:44 UTC, HumairAK commented
> @HumairAK does it make sense to merge this now while MOC is down?

@4n4nd  no let's wait.

2021-01-07 15:58 UTC, 4n4nd commented
@HumairAK I think we can merge this one in now

2021-01-07 16:20 UTC, HumairAK commented
/unhold

2021-01-07 16:21 UTC, merged