Add black flake app.
operate-first/argocd-apps pull request #62
Opened 2021-02-03 12:19 UTC by martinpovolny

Add black flake project app.

To be merged after: https://github.com/aicoe-aiops/ocp-ci-analysis/pull/111

FYI @MichaelClifford 
Please, review @tumido

2021-02-03 12:19 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **martinpovolny** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @martinpovolny` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["martinpovolny"]} -->

2021-02-03 12:44 UTC, tumido commented
/hold wait for the dependency

2021-02-03 12:47 UTC, tumido requested changes

2021-02-03 12:47 UTC, tumido commented on overlays/moc/data-science/black-flake.yml
> +    path: manifests
This spec is missing few keys. You're missing the destination and sync policy etc. See this spec for example:

https://github.com/operate-first/argocd-apps/blob/main/base/operate-first/argo.yaml

You either want to define the full spec in the `base` and overlay the `.spec.source.path` in the overlay/moc (if you aim to deploy this app to different clusters/source path overlays), or define the full spec here.

2021-02-03 15:11 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-02-03 15:18 UTC, HumairAK commented on overlays/moc/data-science/black-flake.yml
> +    path: manifests
I think we need clearer docs on this, I'll set up an issue to improve [this](https://github.com/operate-first/argocd-apps/blob/main/docs/add_application.md)

2021-02-08 08:31 UTC, martinpovolny commented
/unhold

2021-02-08 09:25 UTC, durandom requested changes

2021-02-08 09:25 UTC, durandom commented on overlays/moc/data-science/black-flake.yml
> +    namespace: dc-black-flake
The NS is `ds-black-flake`

2021-02-08 10:05 UTC, martinpovolny commented on overlays/moc/data-science/black-flake.yml
> +    path: manifests
Dest and sync policy added.

2021-02-08 10:05 UTC, martinpovolny commented on overlays/moc/data-science/black-flake.yml
> +    namespace: dc-black-flake
Fixed, thx.

2021-02-08 10:32 UTC, tumido requested changes
One last change is required for this to work properly. LGTM otherwise.

2021-02-08 10:32 UTC, tumido commented on overlays/moc/data-science/black-flake.yml
> +  project: operate-first
The project should be `data-science` since that's the only ArgoCD project which can deploy to `ds-*` namespaces. Also this app resource is placed into the `data-science` folder in this repo, so it doesn't make sense to belong to any other project.

2021-02-08 10:47 UTC, martinpovolny commented on overlays/moc/data-science/black-flake.yml
> +  project: operate-first
Thx, fixed.

2021-02-08 10:56 UTC, durandom approved these changes
/approve

2021-02-08 10:56 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/62#pullrequestreview-585378889" title="Approved">durandom</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-02-08 10:56 UTC, tumido approved these changes
/approve

2021-02-08 10:56 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/argocd-apps/pull/62#pullrequestreview-585378889" title="Approved">durandom</a>*, *<a href="https://github.com/operate-first/argocd-apps/pull/62#pullrequestreview-585379257" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fargocd-apps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/argocd-apps/blob/main/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-02-08 10:57 UTC, merged